const SUPABASE_URL='https://cdavgpvoazbjzgymofcn.supabase.co';
const SUPABASE_KEY='sb_publishable_i_Pc0XGZzA3zGSmhQ-OArw_y0erwjYS';
const OWNER_EMAIL='rs91493234@gmail.com';
const client=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const defaultProjects=[{title:'Student Management System',category:'PYTHON · MANAGEMENT SYSTEM',description:'A practical system for keeping student records organized and easy to manage.',kind:'one',label:'STUDENTS'},{title:'Library Management System',category:'PYTHON · DESKTOP APP',description:'A simple tool to manage books, members, and issue records in one place.',kind:'two',label:'LIBRARY'},{title:'Employee Record System',category:'PYTHON · FILE HANDLING',description:'A straightforward way to create, update, search, and store employee records.',kind:'three',label:'RECORDS'},{title:'Inventory Management System',category:'PYTHON · SQL',description:'A basic system for tracking stock, products, and everyday inventory changes.',kind:'four',label:'INVENTORY'}];
const projectsNode=document.querySelector('#projects'),statusNode=document.querySelector('#save-status'),dialog=document.querySelector('#upload-dialog'),form=document.querySelector('#project-form'),adminDialog=document.querySelector('#admin-dialog'),adminStatus=document.querySelector('#admin-status');let projects=defaultProjects,editingIndex=null,session=null;
const escapeHTML=value=>String(value||'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
const isAdmin=()=>session?.user?.email===OWNER_EMAIL;
const dbProject=p=>({title:p.title,category:p.category,description:p.description||'',url:p.url||'',image:p.image||'',kind:p.kind||'one',label:p.label||p.title.toUpperCase()});
function setStatus(message,type=''){statusNode.textContent=message;statusNode.className=`save-status admin-only ${type}`}
function updateAdminUI(){document.querySelectorAll('.admin-only').forEach(element=>element.hidden=!isAdmin());document.querySelector('#admin-trigger').textContent=isAdmin()?'LOG OUT':'ADMIN LOGIN'}
function renderProjects(){projectsNode.innerHTML='';projects.forEach((p,index)=>{const card=document.createElement('article');card.className='project-card';card.style.animationDelay=`${index*90}ms`;const image=p.image?`<img src="${p.image}" alt="${escapeHTML(p.title)}">`:`<span class="mock">${escapeHTML(p.label||p.title.toUpperCase())}</span><span class="shape"></span>`;const visit=p.url?`<a href="${escapeHTML(p.url)}" target="_blank" rel="noreferrer">VIEW ↗</a>`:'';const edit=isAdmin()?`<button type="button" data-edit="${index}">EDIT</button>`:'';card.innerHTML=`<div class="project-cover ${p.kind||'one'}">${image}</div><div class="project-info"><div><h3>${escapeHTML(p.title)}</h3><p>${escapeHTML(p.category)}</p>${p.description?`<p class="project-description">${escapeHTML(p.description)}</p>`:''}</div><div class="project-actions">${visit}${edit}</div></div>`;projectsNode.append(card)})}
async function loadProjects(){const {data,error}=await client.from('projects').select('*').order('created_at',{ascending:false});if(error){renderProjects();console.error(error);return}projects=data.length?data:defaultProjects;renderProjects()}
function openDialog(index=null){if(!isAdmin())return;editingIndex=index;form.reset();document.querySelector('#dialog-kicker').textContent=index===null?'NEW PROJECT':'EDIT PROJECT';document.querySelector('#dialog-title').innerHTML=index===null?'Publish your <em>project.</em>':'Refine your <em>project.</em>';document.querySelector('#publish-button').innerHTML=index===null?'PUBLISH PROJECT <span>→</span>':'SAVE CHANGES <span>→</span>';document.querySelector('#delete-project').hidden=index===null;if(index!==null){const p=projects[index];['title','category','description','url'].forEach(key=>form.elements[key].value=p[key]||'')}dialog.showModal()}
document.querySelector('#admin-trigger').onclick=async()=>{if(isAdmin()){await client.auth.signOut();session=null;updateAdminUI();renderProjects();return}adminStatus.textContent='';adminDialog.showModal()};
document.querySelector('#admin-form').addEventListener('submit',async event=>{event.preventDefault();adminStatus.textContent='Sending secure login link…';const {error}=await client.auth.signInWithOtp({email:OWNER_EMAIL,options:{emailRedirectTo:window.location.href,shouldCreateUser:true}});adminStatus.textContent=error?'Could not send link. Check Supabase Auth settings.':'Check rs91493234@gmail.com and open the secure login link.';if(error)console.error(error)});
document.querySelector('#open-upload').onclick=()=>openDialog();projectsNode.addEventListener('click',event=>{const button=event.target.closest('[data-edit]');if(button)openDialog(Number(button.dataset.edit))});document.querySelectorAll('.close').forEach(button=>button.onclick=()=>button.closest('dialog').close());
document.querySelector('#delete-project').onclick=async()=>{const project=projects[editingIndex];if(!project?.id||!confirm('Delete this project from your portfolio?'))return;const {error}=await client.from('projects').delete().eq('id',project.id);if(error){setStatus('Could not delete project.','warning');console.error(error);return}projects.splice(editingIndex,1);renderProjects();setStatus('Project deleted.','ready');dialog.close()};
form.addEventListener('submit',async event=>{event.preventDefault();if(!isAdmin())return;const data=new FormData(form),file=data.get('image');let image=editingIndex===null?'':projects[editingIndex].image||'';if(file&&file.size){if(file.size>1500000){setStatus('Please use an image smaller than 1.5 MB.','warning');return}image=await new Promise(resolve=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.readAsDataURL(file)})}const project=dbProject({title:data.get('title'),category:data.get('category'),description:data.get('description'),url:data.get('url'),image,kind:editingIndex===null?'one':projects[editingIndex].kind,label:data.get('title').toUpperCase()});setStatus('Saving project…');const query=editingIndex===null?client.from('projects').insert(project):client.from('projects').update(project).eq('id',projects[editingIndex].id);const {data:saved,error}=await query.select().single();if(error){setStatus('Could not save. Run the security SQL once.','warning');console.error(error);return}if(editingIndex===null)projects.unshift(saved);else projects[editingIndex]=saved;renderProjects();setStatus('Project saved privately.','ready');dialog.close()});
(async()=>{const {data:{session:currentSession}}=await client.auth.getSession();session=currentSession;updateAdminUI();await loadProjects();client.auth.onAuthStateChange((_event,newSession)=>{session=newSession;updateAdminUI();renderProjects()})})();
